from twitchAPI.type import AuthScope

TWITCH_SCOPES = [
    AuthScope.CHAT_READ,
    AuthScope.CHAT_EDIT,
    AuthScope.USER_EDIT,
    AuthScope.USER_READ_EMAIL,
    AuthScope.CHANNEL_SUBSCRIPTIONS,
    AuthScope.MODERATION_READ,
    AuthScope.CHANNEL_READ_REDEMPTIONS,
    AuthScope.CHANNEL_MANAGE_POLLS,
    AuthScope.CHANNEL_MANAGE_PREDICTIONS,
    AuthScope.CHANNEL_READ_POLLS,
    AuthScope.CHANNEL_READ_PREDICTIONS,
    AuthScope.CHANNEL_READ_GOALS,
    AuthScope.MODERATOR_MANAGE_BANNED_USERS,
    AuthScope.MODERATOR_MANAGE_BLOCKED_TERMS,
    AuthScope.MODERATOR_MANAGE_CHAT_MESSAGES,
    AuthScope.MODERATOR_MANAGE_CHAT_SETTINGS,
    AuthScope.MODERATOR_MANAGE_ANNOUNCEMENTS,
    AuthScope.CHANNEL_READ_VIPS,
    AuthScope.MODERATOR_READ_FOLLOWERS,
    AuthScope.CHANNEL_BOT,
    AuthScope.USER_BOT,
    AuthScope.USER_READ_CHAT,
]

DEFAULT_SCOPES = [
    AuthScope.CHAT_READ,
    AuthScope.CHAT_EDIT,
]
