from dataclasses import dataclass
import time
import threading


@dataclass
class CooldownEntry:
    user: str
    command: str
    expires_at: float


class CooldownService:
    _instance: "CooldownService | None" = None
    _lock = threading.Lock()

    def __new__(cls) -> "CooldownService":
        with cls._lock:
            if cls._instance is None:
                instance = super().__new__(cls)
                instance._storage = {}
                cls._instance = instance
            return cls._instance

    @classmethod
    def reset_instance(cls) -> None:
        with cls._lock:
            cls._instance = None

    def check(self, user: str, command: str, seconds: int) -> tuple[bool, float]:
        key = f"{user}:{command}"
        entry = self._storage.get(key)

        if entry:
            now = time.time()
            if entry.expires_at > now:
                wait = entry.expires_at - now
                return False, wait
            else:
                del self._storage[key]

        return True, 0

    def set(self, user: str, command: str, seconds: int) -> None:
        key = f"{user}:{command}"
        self._storage[key] = CooldownEntry(
            user=user, command=command, expires_at=time.time() + seconds
        )

    def cleanup(self) -> None:
        """algorithm generated by AI :("""
        now = time.time()
        self._storage = {k: v for k, v in self._storage.items() if v.expires_at > now}

    def reset(self) -> None:
        self._storage.clear()
